#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  8 16:08:54 2026

@author: animeshkakoty
"""

import numpy as np 
import matplotlib.pyplot as plt

x = [1, 3, 5]

y = np.sin(x)

print(y)

plt.plot(x, y, 'b')

z = np.linspace(-np.pi, np.pi, num = 200)

Z = np.sin(z)

plt.plot(z, Z, 'r', linewidth = 2)

plt.title("the sine curve")
plt.grid()